name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CI: true

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Project
        run: npm run lint
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:cov
  build:
    runs-on: macos-latest
    needs: [lint, unit-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
