name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
      - name: Lint Project
        run: npm run lint
      - name: Build Package
        run: npm run build
      - name: Generate Test Fixtures
        run: npm run generate
      - name: Run Test Suite
        run: npm run test
