name: compatibility-check

on:
  schedule:
    - cron: "21 12 * * 5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
      - name: Build Package
        run: npm run build
      - name: Install latest MSW and OpenAPI-TS versions
        run: npm install msw@latest openapi-typescript@latest
      - name: Print installed MSW version
        run: npm ls msw
      - name: Print installed OpenAPI-TS version
        run: npm ls openapi-typescript
      - name: Generate Test Fixtures
        run: npm run generate
      - name: Run Test Suite
        run: npm run test
