name: compatibility-check

on:
  schedule:
    - cron: "21 12 * * 5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check with MSW v${{ matrix.msw }}
    runs-on: macos-latest
    strategy:
      matrix:
        msw: [2, 3]
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
      - name: Build Package
        run: npm run build
      - name: Install latest MSW v${{ matrix.msw }} and OpenAPI-TS versions
        run: npm install msw@${{ matrix.msw }} openapi-typescript@latest
      - name: Print installed MSW version
        run: npm ls msw
      - name: Print installed OpenAPI-TS version
        run: npm ls openapi-typescript
      - name: Generate Test Fixtures
        run: npm run generate
      - name: Run Test Suite
        run: npm run test
