name: release

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  select-mode:
    if: github.repository == 'christoph-fricke/openapi-msw'
    runs-on: macos-latest
    outputs:
      mode: ${{ steps.select-mode.outputs.mode }}
      publish-plan-artifact-id:
        ${{ steps.select-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
      - name: Select Changesets Mode
        id: select-mode
        uses: changesets/action/select-mode@v2
  version:
    if: needs.select-mode.outputs.mode == 'version'
    needs: select-mode
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
        with:
          skip-cache: true
      - name: Version Package
        uses: changesets/action/version@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: npm run version
          commit-message: "ci: release package"
          pr-title: "ci: release package"
  pack:
    if: needs.select-mode.outputs.mode == 'publish'
    needs: select-mode
    runs-on: macos-latest
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
        with:
          skip-cache: true
      - name: Build Package
        run: npm run build
      - name: Pack Package
        id: pack
        uses: changesets/action/pack@v2
        with:
          publish-plan-artifact-id:
            ${{ needs.select-mode.outputs.publish-plan-artifact-id }}
  publish:
    needs: pack
    runs-on: macos-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Setup CI
        uses: $/.github/actions/setup-ci
        with:
          skip-cache: true
      - name: Publish Package
        uses: changesets/action/publish@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
